spring.application.name=retailsync-api

# Server
server.port=8080

cloud.datasource.url=${CLOUD_DB_URL:jdbc:postgresql://localhost:5432/retailsync_cloud}
cloud.datasource.username=${CLOUD_DB_USER:postgres}
cloud.datasource.password=${CLOUD_DB_PASSWORD:root}
cloud.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:ucanaccess://C:/RetailM/POC_TestShop/recent.mdb;jackcessOpener=com.aximly.retailsync_api.CryptCodecOpener
spring.datasource.driver-class-name=net.ucanaccess.jdbc.UcanaccessDriver
spring.datasource.username=
spring.datasource.password=

mdb.write-exe-path=C:/RetailM/MdbWriter/MdbWriter/bin/Release/net10.0-windows/win-x86/MdbWriter.exe
mdb.file-path=C:/RetailM/POC_TestShop/recent.mdb
mdb.password=

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.HSQLDialect
spring.jpa.show-sql=true

sync.apply-secret=f1420ebc8ce02af0c38c78bc21cfe4f7556e6ae411ee97dea8184c96dca74193

# CORS
cors.allowed-origins=http://localhost:3000

spring.main.lazy-initialization=true